accessControl:
    autologinAs: homeassistant
    autologinLocal: true
    localNetworks:
        - 172.30.32.2
folder:
    data: /data/octoprint/data
    generated: /data/octoprint/generated
    logs: /data/octoprint/logs
    plugins: /data/octoprint/plugins
    printerProfiles: /data/octoprint/printerProfiles
    scripts: /data/octoprint/scripts
    slicingProfiles: /data/octoprint/slicingProfiles
    timelapse_tmp: /tmp
    timelapse: /data/octoprint/timelapse
    translations: /data/octoprint/translations
    uploads: /data/octoprint/uploads
    virtualSd: /data/octoprint/virtualSd
    watched: /data/octoprint/watched
server:
    commands:
        serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
        systemRestartCommand: /restart.sh
        systemShutdownCommand: /shutdown.sh
webcam:
    ffmpeg: /usr/bin/ffmpeg
    snapshot: http://localhost:8080/snapshot
    stream: webcam/?action=stream
system:
    actions:
        -   action: camerastart
            command:  s6-svc -wU -T 5000 -u /var/run/s6/services/mjpg-streamer
            name: Start mjpg-streamer
        -   action: camerastop
            command: s6-svc -wD -d /var/run/s6/services/mjpg-streamer
            name: Stop mjpg-streamer
