accessControl:
    autologinAs: homeassistant
    autologinLocal: true
    localNetworks:
        - 172.30.32.2
folder:
    data: /data/octoprint/data
    generated: /data/octoprint/generated
    logs: /data/octoprint/logs
    plugins: /data/octoprint/plugins
    printerProfiles: /data/octoprint/printerProfiles
    scripts: /data/octoprint/scripts
    slicingProfiles: /data/octoprint/slicingProfiles
    timelapse_tmp: /tmp
    timelapse: /data/octoprint/timelapse
    translations: /data/octoprint/translations
    uploads: /data/octoprint/uploads
    virtualSd: /data/octoprint/virtualSd
    watched: /data/octoprint/watched
server:
    commands:
        serverRestartCommand: /octoprint_restart.sh
        systemRestartCommand: /system_restart.sh
        systemShutdownCommand: /system_shutdown.sh
webcam:
    ffmpeg: /usr/bin/ffmpeg
    snapshot: http://127.0.0.1:8080/?action=snapshot
system:
    actions:
        -   action: camerastart
            command:  /camera_start.sh
            name: Start camera
        -   action: camerastop
            command: /camera_stop.sh
            name: Stop camera
