name: Test ustreamer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test build the Docker image
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target ustreamer
